name: Deploy to AWS ðŸš€

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: KodlarÄ± Ã‡ek
        uses: actions/checkout@v2

      - name: DosyalarÄ± Kopyala
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/ubuntu/halisaha-yonetim-sistemi"

      - name: Docker'Ä± BaÅŸlat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/halisaha-yonetim-sistemi
            # Docker iÅŸlemlerini root yetkisiyle (sudo) yap
            sudo docker compose down || true
            sudo docker compose up -d --build